Provide jobqueue config and example notebook
ExaESM-WP4/dask-jobqueue-configs pull request #8
Opened 2020-02-13 16:46 UTC by kathoef

I have put together a working default Dask jobqueue configuration for JUWELS today (which needs some clean up, but I will do that later). However, as long as https://github.com/dask/dask-jobqueue/issues/382 isn't resolved, opening a Dask jobqueue cluster does not work and we probably should not yet merge this.

(To circumvent the login/compute node interfacing problems, the example notebook was run in an interactive session JupyterLab instance, i.e. JupyterLab also located on a compute node. However, I think this is not a recommended workflow as only full nodes can be allocated on JUWELS and the JupyterLab compute node would be left idling most of the time. Doing calculations locally, i.e. opening a Dask local cluster would avoid this and might be a temporary solution.)

2020-02-13 16:53 UTC, willirath commented
I'm in favor of merging this before the dask issue is solved. After all, this is a working (but not ideal) way of doing this on Juwels for now?

2020-02-14 16:47 UTC, kathoef commented
Thanks, I agree!

2020-02-18 11:21 UTC, willirath requested changes
Looks good. Only one suggestion.

2020-02-18 11:21 UTC, willirath commented on juwels/01_jobqueue_cluster_example.ipynb
> +    "* do an example calculation on larger than memory data"
```suggestion
    "* do an example calculation on larger than memory data",
    "NOTE: Currently, this **only works** if Jupyter is running **on** a **compute node**."
```

2020-02-18 11:29 UTC, willirath approved these changes

2020-02-18 11:29 UTC, merged